NVD_API_KEY 체크

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,6 +38,19 @@ jobs:
           echo "${{secrets.SSL_PRIVATE_KEY_PEM}}" > backend/src/main/resources/secret/ssl/private.key.pem
           echo "${{secrets.SSL_PUBLIC_KEY_PEM}}" > backend/src/main/resources/secret/ssl/public.key.pem
 
+      # CHECK NVD
+      - name: check NVD env
+        working-directory: ./backend
+        env:
+          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
+        run: |
+          if [ -z "$NVD_API_KEY" ]; then
+            echo "::error::NVD_API_KEY is NOT set"
+            exit 1
+          else
+            echo "::notice::NVD_API_KEY is set"
+          fi
+
       # BACKEND BUILD
       - name: build spring boot app
         working-directory: ./backend
